version: "2"
services: 
  nginx:
    container_name: nginx_laravel
    image: nginx:alpine
    build:
      context: ./
      dockerfile: ./docker/web.docker
    volumes:
      - ./www:/var/www
    ports: 
      - 9001:80
    links:
      - php
  php:
    container_name: php_laravel
    build:
      context: ./
      dockerfile: ./docker/app.docker
    volumes:
      - ./www:/var/www
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
    links: 
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testing
    ports:
      - 3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - "MYSQL_USERNAME=root"
      - "MYSQL_ROOT_PASSWORD=secret"
    links:
      - mysql
    ports:
      - "9002:80"